### ISSUE TITLE
Sender phone number is required even SEND_SMS is false

### ISSUE THREAD

**Issue by efe** [Hipo/django-sms-toolkit#10]
https://github.com/Hipo/django-sms-toolkit/blob/master/django_sms_toolkit/models.py#L126

I think that this logic (getting sender phone number) should be in task.

**Comment by alicertel** [comment]
Thank you fixed with the latest release.  I added settings control to mixin.send_sms method not to call sens_sms.delay() method when it's not needed..

**Comment by efe** [comment]
Thank you.
