### ISSUE TITLE
Do not check required twilio fields if SEND_SMS False

### ISSUE THREAD

**Issue by efe** [Hipo/django-sms-toolkit#9]
We check `required_twilio_fields` regardless of `SEND_SMS` flag. I propose to disable this check if the  `SEND_SMS` flag is `False`.

https://github.com/Hipo/django-sms-toolkit/blob/master/django_sms_toolkit/settings.py#L16

**Comment by alicertel** [comment]
Thank you. Fixed with the latest release.

**Comment by efe** [comment]
Thank you, @alicertel .
